name: Run Unit Tests

on: [push, pull_request]

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  start-server:
    needs: setup-environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start REST Server
        run: |
          python main.py &

      - name: Wait for REST Server to start
        run: sleep 10 # Wait for 10 seconds

  run-tests:
    needs: start-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          python -m unittest discover
